# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c4245488529adc95c8fa1770ccfd6050ae3350758144372b62a17a44a304f840fe9754243af8423eabf64fba14b55f3b7de457add64608aca2b702d609347c7

test:
  secret_key_base: 6e56ead4ddf26862fd4ea019cef07316a1872761ca417bab326d0b0dfd2fa1e64645b229283febdc3bc8bcd37fbe430180b5851f2b9645d1c25d66c1a0ce5da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
